dependencies { api project(':dui-core'); compileOnly 'io.papermc.paper:paper-api:26.2.build.129-stable'; testImplementation 'io.papermc.paper:paper-api:26.2.build.129-stable' }
dependencies { implementation 'com.google.code.gson:gson:2.13.2' }
tasks.named('jar') { from(rootProject.file('LICENSE')) { into 'META-INF/dui' }; from(rootProject.file('THIRD_PARTY_NOTICES.md')) { into 'META-INF/dui' } }
