package gg.kembel.dui.core;
/** Generated by scripts/generate-protocol.py; edit protocol/renderer.json. */
public final class RendererProtocol {
 private RendererProtocol(){}
 public static final int VERSION=4;
 public static final int CARRIER_EFFECTS=8;
 public static final int MAX_EFFECTS=32;
 public static final int MOTION_CELLS=48;
 public static final String SCHEMA_SHA256="b86271f4fbd30de3903e7294ccee88e47bc15667209ee7bffd2c4b9253a0b8d1";
 public static final int SHADER_DEFINITION_BITS=6;
 public static final int SHADER_PARAMETER_BITS=240;
 public static final int SHADER_CARRIER_BITS=576;
 public static final int SHADER_MOTION_BITS=99;
 public static final int PLAYER_SIGNATURE=14942208;
 public static final int PLAYER_SIGNATURE_MASK=16515072;
 public static final int PLAYER_RENDERER_BITS=4;
 public static final int PLAYER_BAND_BITS=6;
 public static final int PLAYER_VIEWPORT_BITS=2;
 public static final int PLAYER_POSE_BITS=3;
 public static final int DURATION_OFFSET=0, DURATION_BITS=7;
 public static final int DELAY_OFFSET=7, DELAY_BITS=7;
 public static final int EASING_OFFSET=14, EASING_BITS=2;
 public static final int ENABLED_OFFSET=16, ENABLED_BITS=1;
 public static final int TX_OFFSET=17, TX_BITS=9;
 public static final int TY_OFFSET=26, TY_BITS=9;
 public static final int SCALEFROM_OFFSET=35, SCALEFROM_BITS=8;
 public static final int SCALETO_OFFSET=43, SCALETO_BITS=8;
 public static final int ROTATEFROM_OFFSET=51, ROTATEFROM_BITS=9;
 public static final int ROTATETO_OFFSET=60, ROTATETO_BITS=9;
 public static final int OPACITYFROM_OFFSET=69, OPACITYFROM_BITS=8;
 public static final int OPACITYTO_OFFSET=77, OPACITYTO_BITS=8;
 public static final int PIVOTX_OFFSET=85, PIVOTX_BITS=8;
 public static final int PIVOTY_OFFSET=93, PIVOTY_BITS=8;
 public static final int BASE_DX_OFFSET=0, BASE_DX_BITS=11;
 public static final int BASE_DY_OFFSET=11, BASE_DY_BITS=11;
 public static final int BASE_SIZE_OFFSET=22, BASE_SIZE_BITS=7;
 public static final int BASE_EXPANDED_OFFSET=29, BASE_EXPANDED_BITS=1;
 public static final int HEADER_TICK_OFFSET=0, HEADER_TICK_BITS=15;
 public static final int HEADER_WIDTH_OFFSET=15, HEADER_WIDTH_BITS=9;
 public static final int HEADER_HEIGHT_OFFSET=24, HEADER_HEIGHT_BITS=9;
 public static final int HEADER_X_OFFSET=33, HEADER_X_BITS=9;
 public static final int HEADER_Y_OFFSET=42, HEADER_Y_BITS=9;
 public static final int HEADER_KIND_OFFSET=51, HEADER_KIND_BITS=3;
 public static final int CLIP_X_OFFSET=0, CLIP_X_BITS=10;
 public static final int CLIP_Y_OFFSET=10, CLIP_Y_BITS=10;
 public static final int CLIP_WIDTH_OFFSET=20, CLIP_WIDTH_BITS=9;
 public static final int CLIP_HEIGHT_OFFSET=29, CLIP_HEIGHT_BITS=9;
}
