from pathlib import Path
import json,sys
root=Path(__file__).resolve().parents[1];schema=json.loads((root/'protocol/renderer.json').read_text())
fields=[];offset=0
for name,bits in schema['motionFields'].items():
 if bits<1 or bits>30:raise ValueError('Field width')
 fields.append((name,offset,bits));offset+=bits
if offset>schema['motionCells']*3:raise ValueError('Carrier overflow')
java='package gg.kembel.dui.core;\n/** Generated by scripts/generate-protocol.py; edit protocol/renderer.json. */\npublic final class RendererProtocol {\n private RendererProtocol(){}\n'
for name,key in [('VERSION','version'),('CARRIER_EFFECTS','carrierEffects'),('MAX_EFFECTS','maxEffects'),('MOTION_CELLS','motionCells')]:java+=f' public static final int {name}={schema[key]};\n'
java+=' public static final String SCHEMA_SHA256="'+__import__('hashlib').sha256((root/'protocol/renderer.json').read_bytes()).hexdigest()+'";\n'
glsl='// Generated protocol '+str(schema['version'])+'\n'
for name,value in schema['shaderProfile'].items():
 key='SHADER_'+__import__('re').sub(r'(?<!^)(?=[A-Z])','_',name).upper()
 java+=f' public static final int {key}={value};\n'
 glsl+=f'#define DUI_{key} {value}\n'
glsl+=f"#define DUI_CARRIER_EFFECTS {schema['carrierEffects']}\n"
for name,value in schema.get('playerProfile',{}).items():
 key='PLAYER_'+__import__('re').sub(r'(?<!^)(?=[A-Z])','_',name).upper()
 java+=f' public static final int {key}={value};\n'
 glsl+=f'#define DUI_{key} {value}u\n'
for name,start,bits in fields:
 java+=f' public static final int {name.upper()}_OFFSET={start}, {name.upper()}_BITS={bits};\n'
 glsl+=f'#define DUI_{name.upper()}_OFFSET {start}\n#define DUI_{name.upper()}_BITS {bits}\n'
for prefix,mapping in schema.get('codecFields',{}).items():
 start=0
 for name,bits in mapping.items():
  if bits<1 or bits>30:raise ValueError('Invalid codec width')
  key=prefix+'_'+name.upper()
  java+=f' public static final int {key}_OFFSET={start}, {key}_BITS={bits};\n'
  glsl+=f'#define DUI_{key}_OFFSET {start}\n#define DUI_{key}_BITS {bits}\n'
  start+=bits
java+='}\n'
glsl+='uint duiRead(uvec3 data,int offset,int bits){int word=offset/30,shift=offset%30;uint v=data[word]>>uint(shift);if(shift+bits>30)v|=data[word+1]<<uint(30-shift);return v&((1u<<uint(bits))-1u); }\n'

for path,data in [(root/'dui-core/src/main/java/gg/kembel/dui/core/RendererProtocol.java',java),(root/'dui-pack/src/main/resources/ui/shader/protocol.glsl',glsl)]:
 if '--check' in sys.argv:
  if path.read_text()!=data:raise SystemExit('Stale generated protocol: '+str(path))
 else:path.write_text(data)
